export enum EventType {
	Mouseover = 'mouseover',
	Mouseenter = 'mouseenter',
	Mouseout = 'mouseout',
	Mouseleave = 'mouseleave',
	Mouseup = 'mouseup',
	Mousemove = 'mousemove',
	MouseDown = 'mousedown',
	DblClick = 'dblclick',
	Click = 'click',
	ContextMenu = 'contextmenu',
	KeyDown = 'keydown',
	Keyup = 'keyup',
	Keypress = 'keypress',
	Scroll = 'scroll',
	Resize = 'resize',
	Wheel = 'wheel',
}
